{% set name = "lsd-rust" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsd-rs/lsd/archive/v{{ version }}.tar.gz
  sha256: cd80dae9a8f6c4c2061f79084468ea6e04c372e932e3712a165119417960e14e

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - lsd --help

about:
  home: https://github.com/lsd-rs/lsd
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Clone of ls with colorful output, file type icons, and more
  dev_url: https://github.com/lsd-rs/lsd

extra:
  recipe-maintainers:
    - danielnachun
