{% set name = "lsd-rust" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsd-rs/lsd/archive/v{{ version }}.tar.gz
  sha256: 120935c7e98f9b64488fde39987154a6a5b2236cb65ae847917012adf5e122d1

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - lsd --help

about:
  home: https://github.com/lsd-rs/lsd
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Clone of ls with colorful output, file type icons, and more
  dev_url: https://github.com/lsd-rs/lsd

extra:
  recipe-maintainers:
    - danielnachun
